### ISSUE TITLE
ImportError: Unable to import required dependencies when importing pandas library

### ISSUE THREAD

**Issue by rayguna** [rayguna/pyDEXP#1]
**Issue:** The following error message popped out when importing pandas library:

>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\.conda\envs\finance_py37\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['C:\\Users\\user\\.conda\\envs\\finance_py37\\lib\\site-packages\\numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

**Comment by rayguna** [comment]
**Solution:** As prompted in the error message, the issue is resolved by repeatedly uninstalling numpy and reinstalling, as follows.

- pip uninstall numpy
Found existing installation: numpy 1.21.6
Uninstalling numpy-1.21.6:
  Would remove:
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy-1.21.6.dist-info\*
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\*
    c:\users\ruser\.conda\envs\finance_py37\scripts\f2py.exe
  Would not remove (might be manually added):
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\_import_tools.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\add_newdocs.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\_dummy.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\multiarray.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\multiarray_tests.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\operand_flag_tests.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\struct_ufunc_test.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\test_rational.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\umath.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\core\umath_tests.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\distutils\__version__.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\distutils\compat.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\distutils\environment.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\distutils\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\distutils\site.cfg
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\f2py\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\fft\fftpack.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\fft\fftpack_lite.cp37-win32.pyd
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\fft\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\fft\tests\test_fftpack.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\lib\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\linalg\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\ma\version.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\random\info.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\random\randomkit.h
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\testing\decorators.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\testing\noseclasses.py
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy\testing\nosetester.py
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.21.6

- pip uninstall numpy
Found existing installation: numpy 1.11.3
Uninstalling numpy-1.11.3:
  Would remove:
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy
    c:\users\user\.conda\envs\finance_py37\lib\site-packages\numpy-1.11.3-py3.7.egg-info
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.11.3

- pip uninstall numpy
WARNING: Skipping numpy as it is not installed.

- pip install --upgrade numpy
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-win32.whl (11.7 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.6

- Test:
Python 3.7.7 (default, May  6 2020, 11:43:10) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> 

~
